config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  root 'home#index'

  resources :books
  resources :categories
  resources :authors
  resources :clients
  resources :librarians
  resources :reservations
end

app/views/layouts/_admin_panel_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">    
    
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">           
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_panel_sidebar.html.erb
<aside class="main-sidebar">

  <section class="sidebar">

    <div class="user-panel">
      
      <div class="pull-left info">
        <p>User</p>
        <a href="#"> Online</a>
      </div>
    </div>    

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">MENU</li>
        <li>
          <%= link_to "Reservations", reservations_path%>
        </li>
        <li>
          <%= link_to "Clients", clients_path%>
        </li>
        <li>
          <%= link_to "Books", books_path%>
        </li>
        <li>
          <%= link_to "Authors", authors_path%>
        </li>
        <li>
          <%= link_to "Categories", categories_path%>
        </li>        
        <li>
          <%= link_to "Librarians", librarians_path%>
        </li>
    </ul>
  </section> 
</aside>

app/views/layouts/admin_panel.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Admin | Dashboard</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_panel_header' %>

    <%= render partial: 'layouts/admin_panel_sidebar' %>

    <div class="content-wrapper">      

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section> 
    </div>

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
      </div>
      <strong>Copyright &copy; 2022 <a href="#">Grzegorz Bach</a>.</strong>
    </footer>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Title</title>
  <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top"  role="navigation">
    <div class="container">
      <div id="navbar" class="navbar-toggler" id="navbarSupportedContent" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <ul class="nav navbar-nav me-auto">
          <li class="nav-link"><%= link_to "Home", home_index_path %></li>
          <li class="nav-link"><%= link_to "Reservations", reservations_path%></li>
          <li class="nav-link"><%= link_to "Clients", clients_path%></li>
          <li class="nav-link"><%= link_to "Books", books_path%></li>
          <li class="nav-link"><%= link_to "Authors", authors_path%></li>
          <li class="nav-link"><%= link_to "Categories", categories_path%></li>        
          <li class="nav-link"><%= link_to "Librarians", librarians_path%></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
    <% end %>
    <% end %>

    <div class="main-content">
    <%= yield %>
    </div>
  </div>
  <script>$(".nav-link").on("click", function(){
  $(".nav-link.active").removeClass("active");
  $(this).addClass("active");
});
</script>
</body>
</html>